import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome to the blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the blog
        </h1>

        

        <div>
          <a href="/" >
            <h2>Go Home &rarr;</h2>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
      This is an example of multi zone nextjs app
      </footer>
    </div>
  )
}
