import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Marketplace
        </h1>

        <p className={styles.description}>
          This is the marketplace app
          <code className={styles.code}>/marketplace</code>
        </p>

        <div className={styles.grid}>
          <a href="/blog" className={styles.card}>
            <h2>Blog &rarr;</h2>
            <p>Visit The Blog</p>
          </a>

          <a href="/changelog" className={styles.card}>
            <h2>Changelog</h2>
            <p>Visit Changelog</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        This is an example of multi zone nextjs app
      </footer>
    </div>
  )
}
